Repository FarziPythonic/IIITianFest2022, pull requests merged in 2022-10, with the labels that each got.

#1 Update README.md
  README.md
Labels: hacktoberfest-accepted

#2 added landing page
  index.html
Labels: hacktoberfest-accepted, hacktoberfest

#3 Create styles.css
  styles.css
Labels: hacktoberfest-accepted, hacktoberfest

#6 Create index.html
  Library/index.html
Labels: hacktoberfest-accepted, hacktoberfest

#8 Create library.css
  library.css
Labels: hacktoberfest-accepted, hacktoberfest

#7 Create library.html
  library.html
Labels: hacktoberfest-accepted, hacktoberfest

#5 Create humature.js
  humature.js
Labels: hacktoberfest-accepted, hacktoberfest

#12 Create fest.css
  fest.css
Labels: hacktoberfest-accepted, hacktoberfest

#11 Create fest.html
  fest.html
Labels: enhancement, good first issue, hacktoberfest-accepted, hacktoberfest

#9 Create library.js
  library.js
Labels: enhancement, good first issue, hacktoberfest-accepted, hacktoberfest

#10 maintained
  README.md
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#13 Create profile.html
  profile.html
Labels: enhancement, good first issue, hacktoberfest-accepted, hacktoberfest

#14 Create profile.css
  profile.css
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#17 Create home.css
  home.css
Labels: enhancement, good first issue, hacktoberfest-accepted, hacktoberfest

#16 Create home.html
  home.html
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#15 Create profile.js
  profile.js
Labels: enhancement, good first issue, hacktoberfest-accepted, hacktoberfest
